baseURL = "http://christopherleeds.com"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Chris Leeds"
theme = "docdock"
publishDir = "_site"

[params]
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = false # default is false
themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)


[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>Links</h3>"
name = "<i class='fa fa-github'></i> Github"
identifier = "ds"
url = "https://github.com/cmleeds"
weight = 1

[[menu.shortcuts]]
name = "<i class='fa fa-linkedin'></i> Linkedin"
identifier = "linkedin"
url = "https://www.linkedin.com/in/christopher-leeds-a4392a30/"
weight = 2

[[menu.shortcuts]]
name = "<i class='fa fa-envelope'></i> E-mail"
identifier = "email"
url = "mailto:chris@christopherleeds.com"
weight = 3

[[menu.shortcuts]]
name = "<i class='fa fa-file-text'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 4
